services:
  nodeapp:
    build: .
    container_name: my-node-app
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "2020:2020"
